export enum TransactionCategory {
  FOOD = 'FOOD',
  RENT = 'RENT',
  SHOPPING = 'SHOPPING',
  UTILITIES = 'UTILITIES',
  ENTERTAINMENT = 'ENTERTAINMENT',
  TRANSPORTATION = 'TRANSPORTATION',
  HEALTHCARE = 'HEALTHCARE',
  EDUCATION = 'EDUCATION',
  TRAVEL = 'TRAVEL',
  SAVINGS = 'SAVINGS',
  INVESTMENT = 'INVESTMENT',
  OTHER = 'OTHER',
}

export enum SavingsGoalStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  PAUSED = 'PAUSED',
  CANCELLED = 'CANCELLED',
}
